on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    branches:
      - main
      - develop
name: Build and Test Code
jobs:
  build-artifacts:
    name: Build and Test Java Artifacts
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    # -------------------------
    # Java JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}          
    # -------------------------
    # Maven Build
    - name: Build and run tests
      run: |
        mvn -Prelease verify
    - name: Gathering JAR files
      run: |
        mkdir staging
        find . -path "*/target/*.jar" -exec cp {} ./staging/ \;
    - name: Saving built artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1          
